// ─── Color constants ──────────────────────────────────────────────────────────
// Primary RSMAT brand color (red)
const COLOR_RSMAT_RGB = "197,91,90";
const COLOR_RSMAT_HEX = "#c55b5a";
const COLOR_RSMAT_RGBSTR = "rgb(197,91,90)";

// Error / alert color (bright red)
const COLOR_ERROR_HEX = "#ec2330";

// Neutral transparent background (used for inactive panels)
const COLOR_NEUTRAL_0 = "rgb(150,150,150,0)";

// Semi-transparent white card background
const COLOR_WHITE_60 = "rgba(255,255,255,0.6)";
// ──────────────────────────────────────────────────────────────────────────────

export const config = {
  name: null,
  model: "RSMAT",
  color: COLOR_RSMAT_RGB,
  background_img: new URL("../../img/RSMAT.png", import.meta.url),
  state_background_imgs: {
    percent_100: new URL("../../img/RSMAT_100_BASE.png", import.meta.url),
    percent_75: new URL("../../img/RSMAT_75_BASE.png", import.meta.url),
    percent_50: new URL("../../img/RSMAT_50_BASE.png", import.meta.url),
    percent_25: new URL("../../img/RSMAT_25_BASE.png", import.meta.url),
    percent_0: new URL("../../img/RSMAT_0_BASE.png", import.meta.url),
  },
  css: {
    width: "100%",
  },
  elements: {
    ec_sensor: {
      name: "is_ec_sensor_connected",
      type: "click-image",
      image: new URL("../../img/RSMAT_SENSOR_PLUGGED.png", import.meta.url),
      disabled_if: "${state}==='off'",
      css: {
        width: "100%",
        flex: "0 0 auto",
        position: "absolute",
        transform: "scaleX(1)",
        top: "0%",
      },
      elt_css: {
        width: "100%",
      },
    },
    ec_sensor_disconnected: {
      name: "is_ec_sensor_connected",
      type: "click-image",
      class: "blink-fast",
      disabled_if: "${state}==='on'",
      image: new URL("../../img/RSMAT_SENSOR_UNPLUGGED.png", import.meta.url),
      css: {
        width: "100%",
        flex: "0 0 auto",
        position: "absolute",
        transform: "scaleX(1)",
        top: "0%",
      },
      elt_css: {
        width: "100%",
      },
    },
    unclean_sensor: {
      name: "unclean_sensor",
      type: "click-image",
      class: "blink-color",
      disabled_if: "${state}==='off'",
      icon: "mdi:liquid-spot",
      icon_color: "rgb(128, 64, 0)",
      css: {
        flex: "0 0 auto",
        position: "absolute",
        transform: "scale(2)",
        top: "49%",
        left: "67%",
      },
    },

    last_message: {
      name: "last_message",
      type: "redsea-messages",
      css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "100%",
        height: "15px",
        bottom: "26%",
        left: "0px",
      },
      "elt.css": {
        "background-color": "rgba(220,220,220,0.7)",
      },
    },
    last_alert_message: {
      name: "last_alert_message",
      type: "redsea-messages",
      label: "'⚠'",
      css: {
        color: "red",
        flex: "0 0 auto",
        position: "absolute",
        width: "100%",
        height: "20px",
        bottom: "20%",
        left: "0px",
      },
      "elt.css": {
        "background-color": "rgba(240,200,200,0.7)",
      },
    },
    position: {
      //hidden , force render when position changes
      name: "position",
      type: "common-sensor",
      label: false,
      master: true,
      css: {
        display: "none",
      },
    },
    device_state: {
      name: "device_state",
      type: "click-image",
      icon: "state",
      icon_color: "red",
      master: true,
      tap_action: {
        domain: "switch",
        action: "toggle",
        data: "default",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "0%",
        left: "0%",
      },
    },
    maintenance: {
      name: "maintenance",
      type: "click-image",
      icon: "state",
      icon_color: "red",
      master: true,
      tap_action: {
        domain: "switch",
        action: "toggle",
        data: "default",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "4%",
        left: "0%",
      },
    },
    stats_button_weekly: {
      name: "stats_button_weekly",
      type: "common-button",
      stateObj: null,
      label: "${i18n._('weekly')}",
      tap_action: {
        domain: "redsea_ui",
        action: "update_conf",
        data: {
          stats_week: { css: { display: "none" } },
          stats_month: { css: { display: "block" } },
          stats_button_weekly: { css: { display: "none" } },
          stats_button_monthly: { css: { display: "block" } },
        },
      },
      css: {
        display: "block",
        position: "absolute",
        color: "white",
        "border-radius": "30px",
        "text-align": "center",
        "padding-left": "30px",
        "padding-right": "30px",
        "background-color": COLOR_RSMAT_RGBSTR,
        transform: "skewY(12deg)",
        top: "44%",
        left: "14%",
      },
    },

    stats_button_monthly: {
      name: "stats_button_monthly",
      type: "common-button",
      stateObj: null,
      label: "${i18n._('monthly')}",
      tap_action: {
        domain: "redsea_ui",
        action: "update_conf",
        data: {
          stats_week: { css: { display: "block" } },
          stats_month: { css: { display: "none" } },
          stats_button_weekly: { css: { display: "block" } },
          stats_button_monthly: { css: { display: "none" } },
        },
      },
      css: {
        display: "none", // hidden by default, stats_week is shown first
        position: "absolute",
        color: "white",
        "border-radius": "30px",
        "text-align": "center",
        "padding-left": "30px",
        "padding-right": "30px",
        "background-color": COLOR_RSMAT_RGBSTR,
        transform: "skewY(12deg)",
        top: "44%",
        left: "14%",
      },
    },

    stats_week: {
      name: "stats_week",
      type: "hui-statistics-graph-card",
      conf: {
        type: "statistics-graph",
        entities: [{ entity: "today_usage", color: COLOR_RSMAT_HEX }],
        chart_type: "line",
        period: "hour",
        days_to_show: 7,
        stat_types: ["mean"],
        min_y_axis: 0,
        hide_legend: true,
        logarithmic_scale: false,
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        display: "block",
        top: "42%",
        right: "52%",
        width: "36%",
        height: "36%",
        "--graph-color-1": "red",
        "--ha-card-background": COLOR_WHITE_60,
        "--ha-card-border-width": "0px",
        "--ha-card-box-shadow": "none",
        "box-shadow": "none !important",
        "transform-origin": "top rigth",
        transform: "skewY(12deg) scaleY(0.5)",
      },
    },
    stats_month: {
      name: "stats_month",
      type: "hui-statistics-graph-card",
      conf: {
        type: "statistics-graph",
        entities: [{ entity: "today_usage", color: COLOR_RSMAT_HEX }],
        chart_type: "line",
        period: "day",
        days_to_show: 30,
        stat_types: ["mean"],
        min_y_axis: 0,
        hide_legend: true,
        logarithmic_scale: false,
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        display: "none",
        top: "42%",
        right: "52%",
        width: "36%",
        height: "36%",
        "--graph-color-1": "red",
        "--ha-card-background": COLOR_WHITE_60,
        "--ha-card-border-width": "0px",
        "--ha-card-box-shadow": "none",
        "box-shadow": "none !important",
        "transform-origin": "top rigth",
        transform: "skewY(12deg) scaleY(0.5)",
      },
    },
    wifi_quality: {
      name: "wifi_quality",
      type: "common-sensor",
      master: true,
      label: false,
      icon: true,
      icon_color: COLOR_ERROR_HEX,
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: { type: "wifi" },
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "5.5%",
        height: "2%",
        top: "0%",
        right: "0%",
      },
    },
    configuration: {
      name: "configuration",
      type: "click-image",
      icon: "mdi:cog",
      icon_color: COLOR_ERROR_HEX,
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: {
          type: "config",
        },
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "0%",
        right: "6%",
      },
    },
    remaining_length: {
      name: "remaining_length",
      type: "common-sensor",
      master: true,
      css: {
        position: "absolute",
        "background-color": COLOR_NEUTRAL_0,
        "text-align": "center",
        "padding-left": "30px",
        "padding-right": "30px",
        "padding-top": "5px",
        "padding-bottom": "5px",
        transform: "skewY(8deg)",
        top: "19%",
        left: "20%",
        color: COLOR_RSMAT_HEX,
        "font-weight": "bolder",
      },
    },
    total_usage: {
      name: "total_usage",
      type: "common-sensor",
      css: {
        position: "absolute",
        "background-color": "rgb(150,150,150,0.9)",
        "text-align": "center",
        "padding-left": "20px",
        "padding-right": "20px",
        "padding-top": "4px",
        "padding-bottom": "4px",
        "border-radius": "30px",
        transform: "skewY(6deg)",
        top: "6%",
        left: "38%",
        color: COLOR_RSMAT_HEX,
        "font-weight": "bolder",
      },
    },
    days_till_end_of_roll: {
      name: "days_till_end_of_roll",
      type: "common-sensor",
      prefix: "${i18n._('end_of_roll')}",
      unit: "${i18n._('days')}",
      css: {
        position: "absolute",
        "background-color": COLOR_NEUTRAL_0,
        "text-align": "center",
        "padding-left": "20px",
        "padding-right": "20px",
        "padding-top": "4px",
        "padding-bottom": "4px",
        transform: "skewY(8deg)",
        top: "25%",
        left: "7%",
        color: "rga(75,55,55)",
        "font-weight": "bolder",
      },
    },
    daily_average_usage: {
      name: "daily_average_usage",
      type: "common-sensor",
      prefix: "${i18n._('daily_average')}  ",
      css: {
        position: "absolute",
        "background-color": COLOR_NEUTRAL_0,
        "text-align": "center",
        "padding-left": "20px",
        "padding-right": "20px",
        "padding-top": "4px",
        "padding-bottom": "4px",
        transform: "skewY(10deg)",
        top: "32%",
        left: "21%",
        width: "19%",
        color: COLOR_RSMAT_HEX,
        "font-weight": "bolder",
      },
    },
    total_usage_circle: {
      name: "total_usage",
      target: "remaining_length",
      type: "progress-circle",
      inverted: false,
      target_is_remaining: true,
      colors: {
        center: "rgba(255,255,255,0.5)",
      },
      css: {
        position: "absolute",
        "background-color": COLOR_NEUTRAL_0,
        "text-align": "center",
        "padding-left": "20px",
        "padding-right": "20px",
        "padding-top": "4px",
        "padding-bottom": "4px",
        transform: "skewY(10deg)",
        top: "28%",
        left: "2%",
        width: "12%",
        color: COLOR_ERROR_HEX,
        "font-weight": "bolder",
      },
    },
    auto_advance: {
      name: "auto_advance",
      type: "click-image",
      icon: "state",
      icon_color: COLOR_RSMAT_RGBSTR,
      master: true,
      tap_action: {
        domain: "switch",
        action: "toggle",
        data: "default",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "28%",
        left: "61.5%",
        transform: "scale(1.3)",
      },
    },
    advance: {
      name: "advance",
      type: "common-button",
      icon: "mdi:send",
      tap_action: [
        {
          domain: "button",
          action: "press",
          data: "default",
        },
        {
          domain: "redsea_ui",
          action: "message_box",
          data: "${i18n._('manual_advance')}",
        },
      ],
      css: {
        color: COLOR_RSMAT_RGBSTR,
        transform: "skewY(-10deg) scaleX(1) scale(1.5)",
        position: "absolute",
        top: "26.5%",
        right: "10%;",
      },
    },
    custom_advance_value: {
      name: "custom_advance_value",
      type: "common-sensor",
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: { type: "custom_advance" },
      },
      css: {
        position: "absolute",
        color: COLOR_RSMAT_RGBSTR,
        top: "28%",
        right: "18%",
        transform: "skewY(-10deg)",
        "font-weight": "bolder",
      },
    },
    schedule_advance: {
      name: "scheduled_advance",
      type: "click-image",
      icon: "state",
      icon_color: COLOR_RSMAT_RGBSTR,
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "60%",
        left: "60%",
        transform: "scale(3)",
      },
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: { type: "schedule_advance" },
      },
    },
    mode: {
      name: "mode",
      type: "common-sensor",
      translate_values: true,
      css: {
        position: "absolute",
        "background-color": COLOR_NEUTRAL_0,
        "text-align": "center",
        "padding-left": "20px",
        "padding-right": "20px",
        "padding-top": "4px",
        "padding-bottom": "4px",
        transform: "skewY(10deg)",
        top: "38%",
        left: "9%",
        width: "19%",
        color: "black",
        "font-weight": "bolder",
      },
    },
    end_of_roll: {
      name: "mode",
      type: "click-image",
      disabled_if: "${state}!=='end_of_roll'",
      icon: "mdi:paper-roll",
      class: "blink",
      css: {
        position: "absolute",
        "background-color": COLOR_NEUTRAL_0,
        "text-align": "center",
        "padding-left": "20px",
        "padding-right": "20px",
        "padding-top": "4px",
        "padding-bottom": "4px",
        transform: "skewY(10deg) scale(1.5)",
        top: "18.5%",
        left: "7.5%",
        width: "19%",
        color: "black",
        "font-weight": "bolder",
      },
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: { type: "new_roll" },
      },
    },
    error: {
      name: "mode",
      type: "click-image",
      disabled_if:
        "${state}==='auto' ||  ${state}==='end_of_roll' ||  ${state}==='maintenance' || ${state}==='off'",
      icon: "mdi:alert-decagram",
      icon_color: COLOR_RSMAT_RGBSTR,
      class: "blink-icon",
      css: {
        position: "absolute",
        "background-color": "rgb(250,250,250,1)",
        "text-align": "center",
        transform: "skewY(10deg) scaleX(1.25) scaleY(1.6)",
        top: "34%",
        left: "20.5%",
        color: "black",
        "font-weight": "bolder",
      },
      elt_css: {},
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: { type: "end_error" },
      },
    },
  },
};
