export const config = {
  name: null,
  model: "RSMAT",
  background_img: new URL("../../img/RSMAT.png", import.meta.url),
  state_background_imgs: {
    percent_100: new URL("../../img/RSMAT_100.png", import.meta.url),
    percent_75: new URL("../../img/RSMAT_75.png", import.meta.url),
    percent_50: new URL("../../img/RSMAT_50.png", import.meta.url),
    percent_25: new URL("../../img/RSMAT_25.png", import.meta.url),
    percent_0: new URL("../../img/RSMAT_0.png", import.meta.url),
  },
  css: {
    width: "100%",
  },
  elements: {
    last_message: {
      name: "last_message",
      type: "redsea-messages",
      css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "100%",
        height: "15px",
        bottom: "26%",
        left: "0px",
      },
      "elt.css": {
        "background-color": "rgba(220,220,220,0.7)",
      },
    },
    last_alert_message: {
      name: "last_alert_message",
      type: "redsea-messages",
      label: "'⚠'",
      css: {
        color: "red",
        flex: "0 0 auto",
        position: "absolute",
        width: "100%",
        height: "20px",
        bottom: "20%",
        left: "0px",
      },
      "elt.css": {
        "background-color": "rgba(240,200,200,0.7)",
      },
    },
    position: {
      //hidden , force render when position changes
      name: "position",
      type: "common-sensor",
      label: false,
      master: true,
      css: {
        display: "none",
      },
    },
    device_state: {
      name: "device_state",
      type: "click-image",
      icon: "state",
      icon_color: "red",
      master: true,
      tap_action: {
        domain: "switch",
        action: "toggle",
        data: "default",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "0%",
        left: "0%",
      },
    },
    maintenance: {
      name: "maintenance",
      type: "click-image",
      icon: "state",
      icon_color: "red",
      master: true,
      tap_action: {
        domain: "switch",
        action: "toggle",
        data: "default",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "4%",
        left: "0%",
      },
    },
    stats_button_weekly: {
      name: "stats_button_weekly",
      type: "common-button",
      stateObj: null,
      label: "${i18n._('weekly')}",
      tap_action: {
        domain: "redsea_ui",
        action: "update_conf",
        data: {
          stats_week: { css: { display: "none" } },
          stats_month: { css: { display: "block" } },
          stats_button_weekly: { css: { display: "none" } },
          stats_button_monthly: { css: { display: "block" } },
        },
      },
      css: {
        display: "block",
        position: "absolute",
        color: "white",
        "border-radius": "30px",
        "text-align": "center",
        "padding-left": "30px",
        "padding-right": "30px",
        "background-color": "rgba(236,35,48,1)",
        transform: "skewY(12deg)",
        top: "44%",
        left: "14%",
      },
    },

    stats_button_monthly: {
      name: "stats_button_monthly",
      type: "common-button",
      stateObj: null,
      label: "${i18n._('monthly')}",
      tap_action: {
        domain: "redsea_ui",
        action: "update_conf",
        data: {
          stats_week: { css: { display: "block" } },
          stats_month: { css: { display: "none" } },
          stats_button_weekly: { css: { display: "block" } },
          stats_button_monthly: { css: { display: "none" } },
        },
      },
      css: {
        display: "none", // hidden by default, stats_week is shown first
        position: "absolute",
        color: "white",
        "border-radius": "30px",
        "text-align": "center",
        "padding-left": "30px",
        "padding-right": "30px",
        "background-color": "rgba(236,35,48,1)",
        transform: "skewY(12deg)",
        top: "44%",
        left: "14%",
      },
    },

    stats_week: {
      name: "stats_week",
      type: "hui-statistics-graph-card",
      conf: {
        type: "statistics-graph",
        entities: [{ entity: "today_usage", color: "#c55b5a" }],
        chart_type: "line",
        period: "hour",
        days_to_show: 7,
        stat_types: ["mean"],
        min_y_axis: 0,
        hide_legend: true,
        logarithmic_scale: false,
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        display: "block",
        top: "42%",
        right: "52%",
        width: "36%",
        height: "36%",
        "--graph-color-1": "red",
        "--ha-card-background": "rgba(255,255,255,0.6)",
        "--ha-card-border-width": "0px",
        "--ha-card-box-shadow": "none",
        "box-shadow": "none !important",
        "transform-origin": "top rigth",
        transform: "skewY(12deg) scaleY(0.5)",
      },
    },
    stats_month: {
      name: "stats_month",
      type: "hui-statistics-graph-card",
      conf: {
        type: "statistics-graph",
        entities: [{ entity: "today_usage", color: "#c55b5a" }],
        chart_type: "line",
        period: "day",
        days_to_show: 30,
        stat_types: ["mean"],
        min_y_axis: 0,
        hide_legend: true,
        logarithmic_scale: false,
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        display: "none",
        top: "42%",
        right: "52%",
        width: "36%",
        height: "36%",
        "--graph-color-1": "red",
        "--ha-card-background": "rgba(255,255,255,0.6)",
        "--ha-card-border-width": "0px",
        "--ha-card-box-shadow": "none",
        "box-shadow": "none !important",
        "transform-origin": "top rigth",
        transform: "skewY(12deg) scaleY(0.5)",
      },
    },
    wifi_quality: {
      name: "wifi_quality",
      type: "common-sensor",
      master: true,
      label: false,
      icon: true,
      icon_color: "#ec2330",
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: { type: "wifi" },
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "5.5%",
        height: "2%",
        top: "0%",
        right: "0%",
      },
    },
    configuration: {
      name: "configuration",
      type: "click-image",
      icon: "mdi:cog",
      icon_color: "#ec2330",
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: {
          type: "config",
        },
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "0%",
        right: "6%",
      },
    },
  },
};
