import {
  COLOR_RS_HEX,
  COLOR_RS_RGB,
  COLOR_WHITE_60,
} from "../../../utils/colors";

export const config = {
  name: null,
  model: "RSRUN_RETURN",
  background_img: new URL(
    "../../../img/redsea/RSRUN/reefrun_return.png",
    import.meta.url,
  ),
  css: {
    width: "100%",
    left: "-4%",
  },
  color: COLOR_RS_RGB,
  elements: {
    speed_1: {
      name: "speed",
      type: "progress-circle",
      target: 100,
      put_in: "ctrl_1",
      no_value: true,
      force_integer: true,
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-184.2%",
        left: "77.2%",
        width: "25%",
      },
    },
    speed_2: {
      name: "speed",
      type: "progress-circle",
      target: 100,
      put_in: "ctrl_2",
      no_value: true,
      force_integer: true,
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-184.5%",
        left: "-11.7%",
        width: "25%",
      },
    },
    control_1: {
      name: "schedule_enabled",
      type: "click-image",
      icon: "state",
      put_in: "ctrl_1",
      icon_color: "red",
      click_when_off: true,
      tap_action: {
        domain: "switch",
        action: "toggle",
        data: "default",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-176%",
        left: "84.2%",
      },
    },
    control_2: {
      name: "schedule_enabled",
      type: "click-image",
      put_in: "ctrl_2",
      icon: "state",
      icon_color: "red",
      click_when_off: true,
      tap_action: {
        domain: "switch",
        action: "toggle",
        data: "default",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-176%",
        left: "-4%",
      },
    },
    flow: {
      name: "speed",
      type: "flow-image",
      image: new URL(
        "../../../img/redsea/RSRUN/water_seamless.png",
        import.meta.url,
      ),
      //disabled_if: "entity.schedule_enabled?.state === 'off'",
      class: "tube",
      "animation-name": "flowUp",
      elt_css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "25%",
        left: "41%",
        width: "10%",
        height: "13%",
      },
    },
    pipe_1: {
      name: "missing_pump",
      type: "click-image",
      image: new URL(
        "../../../img/redsea/RSRUN/reefrun_pump_return_pipe.png",
        import.meta.url,
      ),
      put_in: "cables_1",
      elt_css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "57%",
        top: "2%",
        left: "-2.8%",
      },
    },
    pipe_2: {
      name: "missing_pump",
      type: "click-image",
      image: new URL(
        "../../../img/redsea/RSRUN/reefrun_pump_return_pipe.png",
        import.meta.url,
      ),
      put_in: "cables_2",
      elt_css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "57%",
        top: "2%",
        left: "37.2%",
        transform: "scaleX(-1)",
      },
    },
    alim_cable_1: {
      name: "missing_pump",
      type: "click-image",
      image: new URL(
        "../../../img/redsea/RSRUN/reefrun_cable.png",
        import.meta.url,
      ),
      put_in: "cables_1",
      elt_css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "57%",
        top: "-134.5%",
        left: "38.2%",
      },
    },
    alim_cable_2: {
      name: "missing_pump",
      type: "click-image",
      image: new URL(
        "../../../img/redsea/RSRUN/reefrun_cable.png",
        import.meta.url,
      ),
      put_in: "cables_2",
      elt_css: {
        flex: "0 0 auto",
        position: "absolute",
        width: "57%",
        top: "-134.5%",
        left: "-6.1%",
        transform: "scaleX(-1)",
      },
    },
    temperature: {
      name: "temperature",
      type: "common-sensor",
      force_integer: true,
      tap_action: {
        domain: "redsea_ui",
        action: "more-info",
        data: "temperature",
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        color: COLOR_WHITE_60,
        left: "66%",
        top: "62%",
      },
    },
    schedule_1: {
      name: "constant_speed",
      type: "common-schedule",
      schedule_attribute: "schedule",
      time_field: "st",
      value_field: "ti",
      linear: false,
      min_value: 0,
      max_value: 100,
      line_color: "0,150,255",
      fill_alpha: 0.15,
      put_in: "ctrl_1",
      unit: "%",
      label_color: "55,55,55",
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-102%",
        left: "-11%",
        width: "100%",
        height: "100%",
      },
    },
    schedule_2: {
      name: "constant_speed",
      type: "common-schedule",
      schedule_attribute: "schedule",
      time_field: "st",
      value_field: "ti",
      put_in: "ctrl_2",
      linear: false,
      min_value: 0,
      max_value: 100,
      line_color: "0,150,255",
      fill_alpha: 0.15,
      unit: "%",
      label_color: "55,55,55",
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-102%",
        left: "-1%",
        width: "100%",
        height: "100%",
      },
    },
    configuration_1: {
      name: "configuration",
      type: "click-image",
      put_in: "ctrl_1",
      icon: "redsea:cog-1",
      icon_color: COLOR_RS_HEX,
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: {
          type: "config",
        },
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-152%",
        right: "6%",
      },
    },
    configuration_2: {
      name: "configuration",
      type: "click-image",
      put_in: "ctrl_2",
      icon: "mdi:cog-pause",
      icon_color: COLOR_RS_HEX,
      tap_action: {
        domain: "redsea_ui",
        action: "dialog",
        data: {
          type: "config",
        },
      },
      css: {
        flex: "0 0 auto",
        position: "absolute",
        top: "-152%",
        left: "-5%",
      },
    },
  },
};
