/**
 * @deprecated Use "../types/index" directly instead of "base/index"
 * Re-exports all types for backward compatibility
 */
export type {
  HassEntity,
  StateObject,
  HassDevice,
  HassConfig,
  CustomCardDefinition,
  MainDevice,
  DeviceInfo,
  SelectDevice,
  UserConfig,
  DeviceEntity,
  DeviceConfig,
  Device,
  HeadEntity,
  RGB,
  DisabledCondition,
  ActionData,
  Action,
  LabelExpression,
  DynamicValue,
  BaseElementConfig,
  ElementConfig,
  SensorConfig,
  ProgressConfig,
  ButtonConfig,
  DialogContentConfig,
  DialogConfig,
  DialogExtensionFunction,
  DialogExtension,
  RSHTMLElement,
  EvaluationContext,
  SafeEvalContext,
  Schedule,
  ScheduleFixed,
  ScheduleVariable,
  NestedTranslation,
  LanguageDictionary,
  SupportedLanguage,
  I18nConfig,
  HomeAssistant,
  Supplement,
} from "../types/index";
